# Generated by Django 5.1.3 on 2024-11-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="design",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
