# Generated by Django 5.1.3 on 2024-11-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_category_alter_emailtemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#2196f3", max_length=7),
        ),
    ]
